apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - name: kubernetes-manifests
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: ssh
      type: git
      url: git@github.com:example/kubernetes-manifests.git
  url: https://argocd.example.com
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  ports:
    - name: oauth
      protocol: TCP
      port: 9080
      targetPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      imagePullSecrets:
        - name: dockerhub-key
      containers:
        - name: oauth
          image: registry.uw.systems/william/web-server:779082bd66a67abce11aa9bcb537b3544a945141
          args:
            - "--addr=:9080"
            - "--auth-cookie"
            - "--auth-endpoint=https://auth.dev.uw.systems/jwt/staff"
            - "--auth-redirect-url=https://argocd.example.com/__auth/callback"
            - "--auth-verification-keys-url=https://auth.dev.uw.systems/jwt/keys"
            - "--auth-verify-expiry"
            - "--auth-verify-signature"
            - "--proxy=http://localhost:8080/"
            - "--auth-require-scope=https://auth.uw.systems/example-argocd"
