apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # exclude cluster resources for a namespaced install
  #- github.com/utilitywarehouse/argocd-manifests/cluster?ref=<version>
  - ../cluster
  #- github.com/utilitywarehouse/argocd-manifests/namespaced?ref=<version>
  - ../namespaced
resources:
  - applications.yaml
  - argocd-ingress.yaml
  # include in-cluster cluster configuration for a namespaced install
  - secrets/in-cluster.yaml
  - secrets/ssh.yaml
patchesStrategicMerge:
  - argocd-patch.yaml
secretGenerator:
  - name: strongbox
    files:
      - .strongbox_keyring=secrets/strongbox_keyring
