apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # exclude cluster resources for a namespaced install
  #- github.com/utilitywarehouse/argocd-manifests/cluster?ref=<version>
  - ../cluster
  #- github.com/utilitywarehouse/argocd-manifests/namespaced?ref=<version>
  - ../namespaced
resources:
  - applications.yaml
  - argocd-ingress.yaml
  - rbac.yaml
patchesStrategicMerge:
  - argocd-patch.yaml
secretGenerator:
  # include in-cluster cluster configuration for a namespaced install
  - name: in-cluster
    envs:
      - secrets/in-cluster
    options:
      labels:
        argocd.argoproj.io/secret-type: cluster
  - name: ssh
    files:
      - sshPrivateKey=secrets/ssh.pem
    options:
      disableNameSuffixHash: true
  - name: strongbox
    files:
      - .strongbox_keyring=secrets/strongbox_keyring
