kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: example
  - kind: ServiceAccount
    name: argocd-server
    namespace: example
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
