apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/argocd-application-controller.yaml
  - upstream/argocd-config.yaml
  - upstream/argocd-redis.yaml
  - upstream/argocd-repo-server.yaml
  - upstream/argocd-server.yaml
patchesStrategicMerge:
  - argocd-patch.yaml
images:
  - name: argoproj/argocd
    newTag: v1.6.1
