apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/argoproj/argo-cd//manifests/base/application-controller?ref=v1.6.1
  - github.com/argoproj/argo-cd//manifests/base/config?ref=v1.6.1
  - github.com/argoproj/argo-cd//manifests/base/redis?ref=v1.6.1
  - github.com/argoproj/argo-cd//manifests/base/repo-server?ref=v1.6.1
  - github.com/argoproj/argo-cd//manifests/base/server?ref=v1.6.1
patchesStrategicMerge:
  - argocd-patch.yaml
images:
  - name: argoproj/argocd
    newTag: v1.6.1
