apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/argocd-application-controller.yaml
  - upstream/argocd-config.yaml
  - upstream/argocd-redis.yaml
  - upstream/argocd-repo-server.yaml
  - upstream/argocd-server.yaml
patchesStrategicMerge:
  - argocd-patch.yaml
images:
  - name: argoproj/argocd
    newTag: v1.7.6
vars:
  - name: ARGOCD_REDIS_SERVICE
    objref:
      kind: Service
      name: argocd-redis
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
